* **Cod**:

  * :doc:`Bug-uri </contributing/code/bugs>` |
  * :doc:`Patch-uri </contributing/code/patches>` |
  * :doc:`Securitate </contributing/code/security>` |
  * :doc:`Teste </contributing/code/tests>` |
  * :doc:`Standarde de codare </contributing/code/standards>` |
  * :doc:`Convenții </contributing/code/conventions>` |
  * :doc:`Licență </contributing/code/license>`

* **Documentație**:

  * :doc:`Prezentare generală </contributing/documentation/overview>` |
  * :doc:`Format </contributing/documentation/format>` |
  * :doc:`Traduceri </contributing/documentation/translations>` |
  * :doc:`Licență </contributing/documentation/license>`

* **Comunitate**:

  * :doc:`Întâlniri pe IRC </contributing/community/irc>` |
  * :doc:`Alte resurse </contributing/community/other>`
